apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1
- routes/argocd_server_route.yaml
- serviceaccounts/argocd-manager.yaml
patchesStrategicMerge:
- services/argocd_metrics_service_patch.yaml
- services/argocd_server_metrics_service_patch.yaml
- deployments/argocd-repo-server_patch.yaml
- deployments/argocd-server_patch.yaml
- deployments/argocd-dex-server_patch.yaml
images:
- name: argoproj/argocd
  newName: quay.io/operate-first/argocd
  newTag: v2.0.1-1
- name: redis
  newName: quay.io/operate-first/redis
  newTag: 6.2.1-alpine
