kind: ConfigMap
apiVersion: v1
metadata:
    annotations:
        kustomize.config.k8s.io/behavior: merge
    name: cluster-monitoring-config
    namespace: openshift-monitoring
data:
    config.yaml: ENC[AES256_GCM,data:/eRwBDycO8n8dpw88HQRNswo2BBwhtmgyebPPTYCWGOjKhmU8YdDaxU33nNb7ze1oFOaoALANo6hdwUfM7s0XAxbUDwsMIc5WWkqdWzDYOVIxV6mRM66Zy1MakMgbI90isZ1n6zW9KE/4buMV54SWpUb2DjcfulcehkD3tVHKajwp/KcT4xfGYl179UevzFolky85wj2TDDD0B6u/mSY6onnX/9nr9jOBIrzCDZCYFHqJohoXU/+DJvdZXuuIl/qpOl6K/1QBSYy9HQ74zrgxoT369wtnmcHoBD/EYrtizL3qiE0rC1THbJbupD5Idw7ME/1Oyincr/P9uhlLdqt837M3zF3GghHE0CQJHQZwgNaALX+NPKnHfCzYenCq/QmVqzJ0rBtVhHgXHutG6ypfj2qLh5p4a9TVZ+4gVwIT0M5gbgUVsvaY2XRwo5k9ygdbM3bXyW9KU4anZyKlwsASxD8JdZbyvPx0THtwqshqE1sv4uJ54swdzjFe9fTNIzyJtiXk6HvdY6b5uhomgTNPCSJwIr6bvo92PcQr+uYUjLJqrHRB+RHqcJ8Yjo1GDqz4vNusx+LmbmBXNUIZ8iQ8Fn6Euyhw9ArtDBBaMJU34j6giCJfKNiqgI10sB4WYV1/EPHZwIOrDcinP8fz6xO6YPe97ZP+Giauxy1Qdge3ObENTuNXZDb+3oIAJTVtiRwMVP3Y7tEXusX0/65R42feC8zyjho1+HpGENpzJqm5vZAJrQ39qhU/lWdHuEvtRgzTF+GNcfx7KdhgYttfb4BPD8tPsM5srBMVGqqBZE3CH9Mo6Jmjq9uQrQdgPTkqq83nSzOMvSec5kMlRnWW04n/B/yiclhxmgqVhUfG6/yR5VcWcIsTCzKB0UBg1xFuRBuW9VmAUIz/VtBPcRoHZCu+uxaghZlVd9VcwY5cdOuBknjCZ2DlUXugLP5O6vXtvCptSJcVj/7i4jB7OQwZWs/beWDgQvcEccx4DfiacvjbdXRxovy4U9D7mv5ohgJaACNQLd1P0sM15UAczs66SCghcPy+GThnw+Kzb/XR+adsfmNfjMR0J6jTvN+UCBQXv+cdvLRFTH6GAiuqF5sQsSzmL7JIxolaL3PXzhHtqNnKXVhEqVcMVygmDjyFs/f3/KhO5dP7hOO+MxKQMGgfKKLnQ74X6idZZAaK8nMcXbNGgXqva0IywONblLzHRz7UduFO+HQ1XTUe7GX2GyWZdtC+pRr/YdrdJjM5zuBUoXe9KX+1E+y0bAUksXA4krCxDVd3Oy+SspCdguQpa+yJcszW8D661WbyQlipY8nwy70+Bn5aHNcAIHZTQE9i+kxO/6dA4EF0eBh+XoIOWL2fxN1P0flrxnqw99AV5hJ8sov2uF8vBE/HD17uCWPUGpGPjnAfaw4JwCG6WwWndtXDRrNBpL2OCUUpqrfqwOLSC4Rn5PHdrtK/SgMS68NEuV1JZPQehnozN1hF1+Naaxve8fA1O69qf5ex0+yIr9QAIi5KHleQEXnP0Ajt0RJhLgEWO3OKR9FytsTkLRc04feOiDYiQ/rXzN1VQX91SnTVSsyJ214HrHvZHbY2dsxoydPOjMGg5tl+FlveadjyMjby2aj35Ms677zNYV0NE8Stry9gk/aj80pj4wgOcAO86RRfKU3moog0XdWCKzylB6zJ+4w363J1k7qjcBNMrkEwrw6IfLxPxN5i2VmwV9LXcNf22OKrdgUnkCQkVQEbUd6U5hqci/JIbqdLbGzy2m9iNqbQ73dqdBqtK9VOzH20ovnvc8juev+wF4BLCxAZgFIU1HvbTD1k2iw3vL3zgSi57j5rnwkCpyJGSLLiDtBmoW81D67JSjYSNISevfv1YrDftKnFUya8NnEV6IewGdEJpiQM3sQf1R4m4DQFNV5CfnsYAHcsgCe4A8auf3DHNq3dgn6c93HJr6dRNzchmLWUOD6qH3AW/CCGxlkqOY5l1Bob5g2ct9IRbw2z4wydAZqG9Vozu1LIPejwwYh3l9LxOMrfzJlAp9/wdrGWQ4UaxQxvsfhPF0KIDAY8OimjFb1AW7eREgfAXlMFzj8i+pUQjFBJb1t8WuC4NNTgZW2d/3JaQpHTjo/2W/zN6Vr0ap9/fOKRQn55i0xIz1REc5gFfysOyHMspBEj7eUIYk3qT5X1GVXEPtoaLCXmteHpjwoUpun8XTB7TbwT1n3qxCwZ+84LldykREMbIymS915FwgrDkRI5+5ALjT9x7NcVyIpiqh5OE63h/rytjVGZjciAK/QisYEEiby,iv:tdmgCmNfLpVvJBvbUarY4SkF1ZSEEjm6ljEtsS6a7i4=,tag:3ZNl2lZUhzYEdQlxpylDDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-08T21:25:50Z"
    mac: ENC[AES256_GCM,data:8zVZfkb66TxwYLPj/MtUhL9w4O1J4SdB3TVb4yFOK1B/yIgnXwvXlBDX4jotZ5npOG+6CEHFZ6yJn87Qp+VciIxY1KL/fVOcJ0ToAr4A1SFkRqN6v2SJDuKqhyCrNcTcgY27607XsinYsY9+gA0G8g6NIgMHt1ripQojwXUecDw=,iv:W6szdFNzJVrhwdNGr/zeIPUuzgwg4aAt3c8JNTsMda8=,tag:Y3FLBxrOor5GHD6IlXEjoA==,type:str]
    pgp:
        - created_at: "2021-12-03T18:06:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAbuYP5/a6RXhUAKVUJVyd49jlJ8Em0J2b+KeyrM+36+kk
            kvSHU0ft/QwEDmwyqw+4WoSES9YOeXisfdhvsaxIZ2KWxGrDi5jniZ8U8e43Xk3s
            2k5evyOhoixfActkXmU+5kw95QmaNUGm1T2mIi1CuLSyJsYHFNlvQDdOcd+S9g5R
            vTVbV/ETyezaawXCDfphIX4dQxFdItyiqoyvQ4nGTWpfMzEFGH3ZF0jBCErBuW1w
            v4JmvADfqAlpJ9sRSDy6xfWHDY15DinNoUcQ7nEnRNho1Abta/w59jmcYjIVLjZ8
            iJc/JJ0O5pZk9gRv/+GHGS7hS+eAFzK7zyPyZcEs+kVw4vjwOB3Feb69tOF/eb7O
            kRgkQQ2T7mCtQgn0mAB9zTIB/k0OXKn83Klgm6NYYZVo2dqT6EAEfThg+qF94pcx
            TNJ0TCEmwqW9ySfQFeQv7I1/yJinL3qsPVg6olpqmjXJD58r6uJwHKbsWD1g3S1d
            yUVyQE/GclmnkkJRFq1gQgAZj6AyWUwh/pLqZoFSuJcqKjL6q3iySTckCUjcd2iU
            bq/5dukLW9tPjsbubyytBK2sLR7LL+/VTHbdKKW4zyYULyUOmeGq+KuxLo33TGMy
            8RGWbRdFH9g3FoPo15JMHc1kcUtGlB4uwnVJtVYjWvt3LnIX5Dbb3edUvsY1C2zS
            4AHkABNli67edMQsSR1uwiJAmuEHKeDN4K7hTvrg1eIdcrZ24LflStuVzAq8SB13
            tRDdNpk46R9Ki5RZaUJTkDXR3qazuW/g4OQkW1h7SbG36CQOKEBuPDmf4ol3SODh
            ftsA
            =5nzd
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
        - created_at: "2021-12-03T18:06:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAx7mQRst6P0PARAAV+bQys6Z8HDjILvZpo2Hwoap9ogulSsyAUalD7vUCqMv
            kX5OtgBxXm0nyztKvgP5Dlkm2wyH2Wk5ASA5YRongfza4mjEJGcOGvhzivGA5HTl
            XopPXKKOpI2QeAePoXEmVpJDBYSHlzGZJghS+u79Cutl+bghgcuNfLieQMP0rry+
            CrG434wY5BQ2GQfUpv1U05J99+fYUglP1347Jf+Pg/nZIIzJwSG+AOZFQIjXb1gB
            kkzvxe0VtjLhl4S9k1ObrqUMKATMsvKCEoAgWZQgEi/DEbLPzP/QiymmpUsgh9wJ
            cb2VZ/DvuwQSLtmztebrYC5Zu8XcGWHVPErBYLrseSVzHeztt1yjabJzhJaEMeke
            HcfcSb3lf/ntY+waRB0Oh/r9tvul3D4iQD1CVWrUQQTsxzaVx0wgQ73qrpXiVm/s
            eDqNsIecKqHX1+S+UoVypKCvjhaiFKjmUAyCVNIMHl8coQHj00fEI2Mwn0Xef4A+
            2Yb5wOuQEgWAJ9Lyax3+q0PNZiM1ZhOwy/LjL+dpO+SbDaWjBKqBlgNGf7sxZY++
            quBjJiHPFGM1Y8E8M1yDCH9PxmDdElWSmkrVGCom1AqyL2N51xPZlyARggiybNL8
            WTKGygvIA4RMf9ueIHj0uPBR8+6yEQK4jHZLEhcCcRX7DJ06FKTmIDlMeqaoR1/S
            4AHk7J279aTfVz6My8vbc7aHh+HB0eC14Bnh+mDgR+IImhXu4GPlpzRhGbBhBXMI
            SaX17LAZUbdifGD69QMlrFaFq/MGosngWOQrIQks1DqOJHqa5NmfpATC4umzTDLh
            8bEA
            =0mpD
            -----END PGP MESSAGE-----
          fp: 2EB7924D7DA3E2DF4717D3EA9E8653F7D343455A
    encrypted_regex: ^(users|data|stringData)$
    version: 3.7.1
