apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
    name: grafana
spec:
    ingress:
        enabled: true
    baseImage: quay.io/app-sre/grafana:7.1.1
    config:
        security:
            admin_user: "root"
            admin_password: "secret"
        users:
            allow_sign_up: false
            auto_assign_org: true
            auto_assign_org_role: Admin
        auth.anonymous:
            enabled: false
        log:
            level: warn
            mode: console
    dashboardLabelSelector:
    -   matchExpressions:
        -   key: app
            operator: In
            values:
            - grafana
