apiVersion: v1
kind: ResourceQuota
metadata:
  name: thoth-pulp-experiments-custom
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    requests.storage: 60Gi
