---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: odh-message-bus
spec:
  kafka:
    version: 3.1.0
    replicas: 5
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple
    config:
      auto.create.topics.enable: false
      default.replication.factor: 3
      inter.broker.protocol.version: '3.1'
      min.insync.replicas: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 3
      transaction.state.log.replication.factor: 3
    storage:
      type: persistent-claim
      size: 60Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics-config
          key: kafka-prometheus-metrics
  zookeeper:
    replicas: 5
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics-config
          key: zookeeper-prometheus-metrics
  entityOperator:
    topicOperator: {}
    userOperator:
      secretPrefix: kafka-user-
