---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex-dex.apps.devconfus2021.aws.operate-first.cloud/

    storage:
      type: memory

    web:
      http: "0.0.0.0:5556"

    grpc:
      addr: "0.0.0.0:5557"

    telemetry:
      http: "0.0.0.0:5558"

    oauth2:
      skipApprovalScreen: true

    staticClients:

      - id: superset
        name: Superset
        redirectURIs:
          - http://superset.apps.devconfus2021.aws.operate-first.cloud/oauth-authorized/dex
          - https://superset.apps.devconfus2021.aws.operate-first.cloud/oauth-authorized/dex
        secretEnv: SUPERSET_SECRET

      - id: trino
        name: Trino
        redirectURIs:
          - https://trino-route-opf-trino.apps.devconfus2021.aws.operate-first.cloud/oauth2/callback
          - https://trino.apps.devconfus2021.aws.operate-first.cloud/oauth2/callback
        secretEnv: TRINO_SECRET

    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://kubernetes.default.svc
          clientID: system:serviceaccount:dex:dex
          clientSecret: $OPENSHIFT_CLIENT_SECRET
          redirectURI: http://dex-dex.apps.devconfus2021.aws.operate-first.cloud/callback
          groups:
            - system:authenticated
