---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: app-logs
      type: kafka
      url: tls://odh-message-bus-kafka-bootstrap-opf-kafka.apps.zero.massopen.cloud:443/zero-prod.cluster-logs.application
      secret:
        name: clo-kafka
  pipelines:
    - name: forward-app-logs
      inputRefs:
        - application
      outputRefs:
        - app-logs
        # default outputref sends logs to the default CLO ES
        - default
    - name: forward-infra-logs
      inputRefs:
        - infrastructure
      outputRefs:
        - default
    - name: forward-audit-logs
      inputRefs:
        - audit
      outputRefs:
        - default
