apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/openshift-distributed-tracing
  - ../../base/operators.coreos.com/subscriptions/jaeger-operator
