apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: osc-cl1
    namespace: openshift-ingress
  project: cluster-management
  source:
    repoURL: https://github.com/operate-first/apps.git
    path: cert-manager/overlays/route53/us-east-1/osc-cl1
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
