---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: odh-monitoring
  labels:
    app: prometheus
    prometheus: k8s
spec:
  serviceMonitorSelector: {}
  securityContext: {}
  ruleSelector: {}
  replicas: 2
  retention: 7d
  remoteRead:
    - url: "http://prometheus-operated.opf-jupyterhub.svc.cluster.local:9090\
            /api/v1/read"
    - url: "http://prometheus-operated.opf-observatorium.svc.cluster.local:9090\
            /api/v1/read"
