apiVersion: v1
kind: ResourceQuota
metadata:
  name: opf-trino-custom
spec:
  hard:
    limits.cpu: '8'
    limits.memory: 40Gi
    requests.cpu: '4'
    requests.memory: 40Gi
    requests.storage: 20Gi
    count/objectbucketclaims.objectbucket.io: 1
