apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
components:
    - ../../../../components/project-admin-public-authenticated
    - ../../../../components/limitranges/default
namespace: devconfcz-2022-demo
