---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - configmaps/cluster-monitoring-config.enc.yaml
  - configmaps/user-workload-monitoring-config.enc.yaml
  - secrets/image-registry-private-configuration-user.enc.yaml
  - secrets/rook-ceph-external-cluster-details.enc.yaml
