---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codait-advo

resources:
- namespace.yaml

components:
- ../../../components/project-admin-rolebindings/codait-advo
- ../../../components/limitranges/default
- ../../../components/resourcequotas/small
