apiVersion: v1
kind: ConfigMap
metadata:
  name: odh-jupyterhub-sizes
  labels:
    jupyterhub: singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
      sizes:
      - name: Extra Large - Memory intensive
        resources:
          requests:
            memory: 16Gi
            cpu: 100m
          limits:
            memory: 48Gi
            cpu: 4
