apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
    name: devconfus2021
    labels:
        client: devconfus2021
spec:
    client:
        clientId: ENC[AES256_GCM,data:ILip2E/8rfjLI/d3FQ==,iv:3UJUIuAOPMagr044QzgjQeqhUkFafhWVqKf0a8l0Ryo=,tag:Qm8ECYSBJCint5zl//scXg==,type:str]
        defaultClientScopes:
        - profile
        description: DevConf.US 2021 OpenShift cluster
        name: DevConf.US 2021 cluster
        protocol: openid-connect
        secret: ENC[AES256_GCM,data:F0fPeng5/r8RdVsMz9JAndjttUTVJQ2t4+5boryV4QPoGMZ1,iv:ZaoqKiH1isEVAoRzDDXQdA9dOSNKjIc9RmZ1pkLX5w8=,tag:8fR517GEBYfD1LhfFSiY4w==,type:str]
        standardFlowEnabled: true
        redirectUris:
        - https://oauth-openshift.apps.devconfus2021.aws.operate-first.cloud/oauth2callback/operate-first
    realmSelector:
        matchLabels:
            realm: operate-first
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-08-30T15:27:50Z'
    mac: ENC[AES256_GCM,data:GdVqhJ3Tl5cNke/865RjGSiJUDBfPwhxBSjiasFZICuKzNqYgK7MgalF/2LnUbT77yLz8PaFXS5Ww6XzuuhiV6un0VwjNvSk/ulbZ771XcwNVi8nWOu/HfTH7wPorf9/3G39X5eQ7Gs/FMZfobJzo7SKNVVyvFgrBf4MoajcxT8=,iv:Y6TZ90NLhFvhb58FXVzvMwfzgzL6YNGkkPnAt+5P09k=,tag:+icn61VamS14NyiY/KPE4A==,type:str]
    pgp:
    -   created_at: '2021-06-16T22:13:59Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAtsJvD2FFO724wGspw+1StnWk+JlkyuCE78UMQ3ajoWzV
            M0qNbaqd1eBWiuyXwPJHm/6YPmVmSrKgo857IBXmU8NEsTAs3PyxZ7W7t7tE6COX
            xZrW8gle2a7RbDAnJ9mvV16RA/xXQnKnu9hqOlMqWU/qvjsM6nS0UVHiaFvy0nYq
            gbWv4XAa/Z0ygwozq7/sKvfVYoB8zc/sztMwjU041ogdzpmKAidO7pn5w/ONKalG
            y/NcLMZl9ckNBgiwAVLebequZuQ4omxj7zWV6qppfLRC23+tJQRGQYOjE97brBKM
            iJIuWKIrDuhApTZ+voXgZDap81qolJADaQ4zcSYEmvVP1druUNaDdOIUpF0dOsEX
            38UMtwDj4J725J24ouUVvVUYcOkig7p59z0OaIEXTeKME2WWp5IDxbF6EFrBWnDy
            82L2yzr6Ch1pEVqINJjBF4Qg8pqbio4qrSGg5HrHLghFAAV0wUS24ILbDbbilKYI
            CjBQbhitIs8vdv6kAwmisTLRWSNB+VXEFEnjfjL8V3Hn0PyQ+91qP9fslPkPpW22
            6iJbHPahSk9D7xuOwAnehiNXhW+ZYiv5reMu31j4XYZ+gpLSTtJNSMF0STzHlkoa
            d7JRKr0ugQXuCnWP4ahFzCtDlrDkpg0Ljmx34dgK4uQpiBKAw6LrH/7q22OPTVvS
            5gGCoxfykfXsmTEAPShfg8st5p0BrA608yFLfgYzh0p6HtK0WqcWDjBS1mE2BWrl
            wKOxlBtYOBYW3aaJCPRmbbPk8ZK33s6oZZ3N7edqmFjX9+IuI/VKAA==
            =BcQ5
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(clientId|clientSecret|secret)$
    version: 3.7.1
