apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
    name: devconfus2021
    labels:
        client: devconfus2021
spec:
    client:
        clientId: ENC[AES256_GCM,data:ILip2E/8rfjLI/d3FQ==,iv:3UJUIuAOPMagr044QzgjQeqhUkFafhWVqKf0a8l0Ryo=,tag:Qm8ECYSBJCint5zl//scXg==,type:str]
        defaultClientScopes:
            - profile
        description: DevConf.US 2021 OpenShift cluster
        name: DevConf.US 2021 cluster
        protocol: openid-connect
        secret: ENC[AES256_GCM,data:l8RGojGw8Rk19zB5GB71M1W0S7704vHLvF/nyu+9M08hwIId,iv:1f+iWPkBrjotm5CvX9TLrU5qyDYSqmWiza2xA8NthIc=,tag:zQAfBkMBj5p9fFePLW+QEQ==,type:str]
        standardFlowEnabled: true
        redirectUris:
            - https://oauth-openshift.apps.devconfus2021.aws.operate-first.cloud/oauth2callback/operate-first
    realmSelector:
        matchLabels:
            realm: operate-first
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-30T10:53:10Z"
    mac: ENC[AES256_GCM,data:84yPQJtI/W9a8SpkoRZ21LfvG1F8bFVqUqZznLYmgErAFrh3Q9kxtQ7h/18hmssKGyG9OTd/o9nWHkb6u9qe28w0NtaKSt4qPAqDHZ9DabRv5qkyZ0oWTVAg+/1WqJlQjhDYK5hdBBKgOsc+kiVy9pVo4RR3Emn/Pqh6ZJKo/Rk=,iv:VTzhdp8wxJVz9Ab4HOAOL8ghrRL6VDS3E4WpMfCUii4=,tag:KVMDGvS4jiV9uROtSLr1HA==,type:str]
    pgp:
        - created_at: "2021-06-16T22:13:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAtsJvD2FFO724wGspw+1StnWk+JlkyuCE78UMQ3ajoWzV
            M0qNbaqd1eBWiuyXwPJHm/6YPmVmSrKgo857IBXmU8NEsTAs3PyxZ7W7t7tE6COX
            xZrW8gle2a7RbDAnJ9mvV16RA/xXQnKnu9hqOlMqWU/qvjsM6nS0UVHiaFvy0nYq
            gbWv4XAa/Z0ygwozq7/sKvfVYoB8zc/sztMwjU041ogdzpmKAidO7pn5w/ONKalG
            y/NcLMZl9ckNBgiwAVLebequZuQ4omxj7zWV6qppfLRC23+tJQRGQYOjE97brBKM
            iJIuWKIrDuhApTZ+voXgZDap81qolJADaQ4zcSYEmvVP1druUNaDdOIUpF0dOsEX
            38UMtwDj4J725J24ouUVvVUYcOkig7p59z0OaIEXTeKME2WWp5IDxbF6EFrBWnDy
            82L2yzr6Ch1pEVqINJjBF4Qg8pqbio4qrSGg5HrHLghFAAV0wUS24ILbDbbilKYI
            CjBQbhitIs8vdv6kAwmisTLRWSNB+VXEFEnjfjL8V3Hn0PyQ+91qP9fslPkPpW22
            6iJbHPahSk9D7xuOwAnehiNXhW+ZYiv5reMu31j4XYZ+gpLSTtJNSMF0STzHlkoa
            d7JRKr0ugQXuCnWP4ahFzCtDlrDkpg0Ljmx34dgK4uQpiBKAw6LrH/7q22OPTVvS
            5gGCoxfykfXsmTEAPShfg8st5p0BrA608yFLfgYzh0p6HtK0WqcWDjBS1mE2BWrl
            wKOxlBtYOBYW3aaJCPRmbbPk8ZK33s6oZZ3N7edqmFjX9+IuI/VKAA==
            =BcQ5
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(clientId|clientSecret|secret)$
    version: 3.7.1
