apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
    name: infra
    labels:
        client: infra
spec:
    client:
        clientId: ENC[AES256_GCM,data:c7v8Yo4=,iv:n2vstDwAfcHUWPLdGZbA8EZL+Jq4JhAXtO8UAg+X3Zo=,tag:FbKvSfoNaAzPMsX/ogqSuw==,type:str]
        defaultClientScopes:
        - profile
        description: MOC-Infra OpenShift cluster
        name: Infra cluster
        protocol: openid-connect
        secret: ENC[AES256_GCM,data:VcED8BEFjRB38TWXOSEhCLqw8Q0vqj6DPrrjleiX0uVaZcMF,iv:cewrWVwTsZK89O7AbeTipCLEAepbMbEthfazjbTMC8I=,tag:fM0QjqkQRunkCOgXPwiLRw==,type:str]
        standardFlowEnabled: true
        redirectUris:
        - https://oauth-openshift.apps.moc-infra.massopen.cloud/oauth2callback/operate-first
    realmSelector:
        matchLabels:
            realm: operate-first
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-08-17T20:21:22Z'
    mac: ENC[AES256_GCM,data:FBkSHagG128JX8/kpn86GjhItO7HvcjkeArvkMjJyw8V2MRmGL2MFR5W6BrdS5XKtu2FWtUAfCf0bVkISKNl0jW4Y46EX5CWcKU5h5zZteblbrdssFPYvjS15Bh1xZXzcudcFDM5SYG3zPcK76TbF/EXDgy0wha3B6BZWMNZ+qo=,iv:ozaW2GbFflggPqNTGFU435Xr9pF9cQyDxns3KzcQH7E=,tag:dnpbUDF/TUetkRkaUuEXAQ==,type:str]
    pgp:
    -   created_at: '2021-06-16T22:14:13Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAD8Z8L94uRoDeNZrN/FoJuXbPd4ntDm0ID7sLKeZSoyF8
            zWfYCWgy5C937chgUETeqQLRPldXQzVEWizUC/unZKlAp1UaYcKAPOyb9GDsV/Ph
            166hDp/kUbzVLeORp8vWWfJMGHPAZqgY2baf6ccxiNDroHut8lP2oRlB+3Ffg/rE
            Hk5IQBmG8LxAj/EaPbviiM26o5sCyuDJks3JhSF997oYt91YaU+Qs4Em/YaZUm16
            ZfFGSG8jcShSKUzFORRVYw61QOgseV2bNtmhvTvJ7NJy+cln4BRj/fzwiEVKLOsm
            PDg5IosyQQtThrZdCAWOxnyPsAsCjSvX5aoSHD2FNs65sHlCSlcR1ookvMY5v043
            meK97pGZ4KbSRXiqTUoiC7XRTvsbEq5pF5hdYL4eWCdQ++Jn5Qg7TxOs3iZs8KC6
            Hn7bZFP6eQ8tWNWSecnJ3VC1EjwvVmkaJuwIoU1wLt3AO5InEE1gIJpKHdQ4HzYw
            atjozxMR8KvbpDUML7NR7NQPDKMq7UTmFf52rCWC6BEDMwPHi026+3nasTC0l6s/
            WMqwpcpDnLLQhtOWG/+SLIIqEWoM0Fbl0kswpWBR/+F1EM/ujmHVXGv13EBBqWpK
            BkYzlP1EvVrMR+hYaSj2qZijBfv19s3V+5Tpy6CfmasVDzPaPJyrUpalOOiS+n/S
            5gGkyvlembVi4ytO78qCWupzCi1YWRhp9Mj0psh+2i+RskL+Hg4RhQEuR3+D31Iu
            /cEcBasqnRfyUb+k0MCr58PkPpA6Fp3moGiJZ9AnSoEWleI03qubAA==
            =jtw2
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(clientId|clientSecret|secret)$
    version: 3.7.1
