apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
spec:
  project: cluster-management
  source:
    chart: volsync
    repoURL: https://backube.github.io/helm-charts
    targetRevision: 0.3.0
    helm:
      releaseName: volsync
  destination:
    server: smaug
    namespace: open-cluster-management-agent
