---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - datasource.yaml
  - grafana.yaml
  - grafana-datasource.yaml
  - route.yaml

generators:
  - secrets-generator.yaml
