---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana
spec:
  to:
    kind: Service
    name: grafana-service
  port:
    targetPort: oauth-proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
