---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false

    discovery-server.enabled=true
    discovery.uri=http://localhost:8080

    web-ui.authentication.type=oauth2
    http-server.authentication.type=PASSWORD,oauth2
    http-server.process-forwarded=true
    http-server.http.port=8080
    http-server.https.port=8443
    http-server.https.keystore.path=/etc/pki/tls/cert.pem
    http-server.authentication.oauth2.auth-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/auth
    http-server.authentication.oauth2.token-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/token
    http-server.authentication.oauth2.jwks-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/keys
    http-server.authentication.oauth2.client-id=trino
    http-server.authentication.oauth2.client-secret=${ENV:TRINO_OAUTH_SECRET}
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  log.properties: |-
    io.trino=INFO
  node.properties: |-
    node.environment=$(trino_environment)
    node.data-dir=/tmp/data/trino
  password-authenticator.properties: |-
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
  password.db: |-
    admin:$2y$10$BTdeo7kp7/SgZ70GWax6k.fjXGLV1tXTuPa8vI6UYL2bTc27kwgnW
    erik:$2y$10$nsahOM613DwrD/xTVl87iO6V91X971ZtLD9bFLblwTMhQL9V6OG.y
    mikhail:$2y$10$Nigz322DgUfja26w3AsPh.kd2osn80KG/At6iDNXQSL7ZEthy17JO
    hukhan:$2y$10$64fLBHs8oy7NdxbYIElpQectw5vSwJdfmF4WLOrvuqBO4Ef3DCaMS
    ricardo:$2y$10$hKFprvQUmoLC9.Oz75MGOu10PJwq776tL/x4tsSEID18XJHKQiatW
    vincent:$2y$10$vLS2A32P.WiFwHHxtnM.WO08s7FkbUI5CdLrOTeDEwthcOXpNSx4y
  group-provider.properties: |-
    group-provider.name=file
    file.group-file=/etc/trino/group-mapping.properties
  group-mapping.properties: |-
    admins:admin,erik
    urgentem:erik,mikhail,ricardo,vincent
    team1:hukhan
    team2:mikhail
  access-control.properties: |-
    access-control.name=file
    security.config-file=/etc/trino/rules.json
  rules.json: |-
    {
      "catalogs": [
      {
        "group": "admins",
        "allow": "all"
      },
      {
        "group": "team1|team2",
        "allow": "read-only"
      },
      {
        "allow": "none"
      }
      ],
      "schemas": [
      {
        "group": "admins",
        "owner": true
      },
      {
        "owner": false
      }
      ],
      "tables": [
      {
        "group": "admins",
        "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
      },
      {
        "group": "team1",
        "catalog": "hive",
        "schema": "team1",
        "privileges": ["SELECT"]
      },
      {
        "group": "team2",
        "catalog": "hive",
        "schema": "team2",
        "privileges": ["SELECT"]
      },
      {
        "privileges": []
      }
      ]
    }
