apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.6
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
  desiredUpdate:
    image: quay.io/openshift-release-dev/ocp-release@sha256:f07ba64a24638e3bf8ff5d71b6f5bd400ed4501ed4aadf5f3a36ecda1ea75ec6
    version: 4.6.31
