apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
spec:
  destination:
    name: smaug
    namespace: api-designer
  project: apicurio
  source:
    path: manifests/api-designer/operate-first
    repoURL: https://github.com/Apicurio/apicurio-operate-first
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - Validate=false
