apiVersion: v1
kind: Secret
metadata:
    name: moc-sso-client-secret
    namespace: openshift-config
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:uPp2EhACgd1zyOfzDNFnuRUEDSi166bqfSehQCAvP9NI/TSs,iv:11w6dxOf2Pq3suxHlE/74aYv6xEtMK3X5bpFmZOpR9k=,tag:otzuBpXzuozUQFjDPqeWYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-08T12:55:05Z'
    mac: ENC[AES256_GCM,data:xsQxqWmcUm3Cdxl0iRIaiLY+f1tE0naxUC2UKBH4LB8hF6VmVfzPLdiFj2WwIccm6mzlzt1PMjkPuhlcgp9eY0Vo+7N3wPh9Vi3Xxuwru7Qo6aVWyEAlQW588fUi2kWb078cx2plRrFysCzL7QWaoUNcvnP2bmXkJChNIepjq94=,iv:Ua/ptB9cJWwU0R0jgNUnphu3xvUEXY/pZErYgXdPOP0=,tag:BHX7k1y2AfX1x0L/c7brAw==,type:str]
    pgp:
    -   created_at: '2021-02-18T18:10:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//X4tN8TBOdIYYFSeUVgDhIBI7+sWJ96RxYZ1mT9DSXX51
            /Tyh4synjpjB6dePQnke54gOC+IBoccZhbyktVAmsbV+cA+C1kEy8VnTdsDcKtMR
            9/ti7InJhSPszKb3TkdfMoi1c4YqANCPY9jzm1QJQO7KXBRPL50MfDLdp0Km35Al
            mZz235u2tyiNmz2PC1jCyAJ12hAYt0zJk15abyYEHiDaiK4DVgSOzkTGT+s1II7x
            blccWeCExVXOBo3qFOkXbQbrtTTeYj5FnQt20quAPAE34GDy5HZS20eMZKUzNkxr
            sZQzBzAdsTp8VyyusgO9122B7hvfbgHJc5jfMZR14/5WU5dDfjx0/52+yfxcxsPF
            1W03dKbaYMNBRDpsRrXDvhxdWjr43kqYg5R3jFcMsZAFZrqEqZNuwklR9MLY79ar
            lzt6/5yR8+lWYi2+I34DwQVZK+6Vq8NAbG/WJZeMM1Aef21ffMjMl2ZhZJcu179X
            UoyzAUCrhoPY3/Ytk01/YgxbscYnui2Yswkd95rkbiRZTiJWhOiZIY8Vmj3BClx4
            AL6kMRIysEQ7AOXY5pkS1mIw2xjmaY8KmGUpp/NZ5aSmy6gXmyw7KVlmjTFtf3qa
            47Wi+NzBu54vAISAPnznRW/+14RJzuV3zBdmHIF05KTXyy2xA463Mg/P67rpeePS
            XgEi/AXYCwvkKZfclBlOxn7No7f7Qo0BdhXpVSEbXvnV2aWdJRMO53YFkHGePzbT
            AkB2zU6rnO5ZgXT7UfywE52yepKAk1WKTfiOFDXazfkJOOjhdXGZmiKABfFRBFg=
            =gjja
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(users|data|stringData)$
    version: 3.6.1
