apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jupyterhub-idle-culler
spec:
  selector:
    app: jupyterhub-idle-culler
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub-idle-culler
    spec:
      containers:
        - name: jupyterhub-idle-culler
          command:
            - jupyterhub-idle-culler
            - --timeout=259200  # 3 days
            - --url=https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/api
