apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: thoth
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          # this user has access to all topics with "thoth-" prefix
          name: thoth-
          patternType: prefix
          type: topic
        type: allow
    type: simple
