---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-jupyterhub

resources:
  - ../../../../base/jupyterhub

patchesJson6902:
  - patch: |
      - op: replace
        path: /spec/applications/2/kustomizeConfig/repoRef/path
        value: odh-manifests/ai4ci/jupyterhub
    target:
      group: kfdef.apps.kubeflow.org
      kind: KfDef
      name: opendatahub
      version: v1
