---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-oauth-proxy.yaml
  - loki-distributor.yaml
  - loki-query-frontend-oauth-proxy.yaml
  - thanos-query-frontend-oauth-proxy.yaml
