---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uky-hpc-workload-generator

resources:
- namespace.yaml

components:
- ../../../components/project-admin-rolebindings/uky-redhat
