apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertreceiver
spec:
  destination:
    name: morty
    namespace: opf-alertreceiver
  project: cluster-management
  source:
    path: alertreceiver/overlays/emea/morty
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
