---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf
spec:
  destination:
    name: morty
    namespace: openshift-storage
  project: cluster-management
  source:
    path: odf/overlays/emea/morty
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - Validate=false
