---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://$DEX_ROUTE/api/dex

    storage:
      type: memory

    web:
      http: "0.0.0.0:5556"

    grpc:
      addr: "0.0.0.0:5557"

    telemetry:
      http: "0.0.0.0:5558"

    oauth2:
      skipApprovalScreen: true

    staticClients:
      - id: superset
        name: Superset
        redirectURIs:
          - $SUPERSET_URI
        secretEnv: SUPERSET_SECRET

      - id: trino
        name: Trino
        redirectURIs:
          - $TRINO_URI
        secretEnv: TRINO_SECRET

      - id: grafana
        name: Grafana
        redirectURIs:
          - $GRAFANA_URI
        secretEnv: GRAFANA_SECRET

    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://kubernetes.default.svc
          clientID: system:serviceaccount:opf-auth:dex
          clientSecret: $OPENSHIFT_CLIENT_SECRET
          redirectURI: $OCP_REDIRECTURI
          groups:
            - system:authenticated
