apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: namespace-view-ocp-pipelines-sre
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: ocp-pipelines-sre
