---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/apiextensions.k8s.io/customresourcedefinitions/kfdefs.kfdef.apps.kubeflow.org
  - ../../../../base/core/namespaces/acme-operator
  - ../../../../base/core/namespaces/dex
  - ../../../../base/core/namespaces/kubeflow
  - ../../../../base/core/namespaces/opendatahub-operator
  - ../../../../base/core/namespaces/odh-jupyterhub
  - ../../../../base/core/namespaces/odh-superset
  - ../../../../base/core/namespaces/odh-trino
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/opendatahub-operator
  - ../../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
  - ../../../../base/rbac.authorization.k8s.io/clusterroles/opendatahub-operator
  - ../../../../base/user.openshift.io/groups/odh-admin
  - ../../../../base/user.openshift.io/groups/odh-users
  - ../../../../base/user.openshift.io/groups/cluster-admins

patchesStrategicMerge:
  - groups/odh-admin.yaml
  - groups/odh-users.yaml
  - groups/cluster-admins.yaml
