apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-cert.yaml
  - default-ingress-cert.yaml
  - openshift-ingress-issuer.yaml
  - openshift-api-issuer.yaml

generators:
  - secret-generator.yaml
