---
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  name: opendatahub
spec:
  applications:
    # ODH-Common components
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    # Kubeflow Pipeline components
    - kustomizeConfig:
        repoRef:
          name: pipeline-manifests
          path: pipeline/api-service
      name: api-service
    - kustomizeConfig:
        overlays:
          - openshift
        parameters:
          - name: minioPvcName
            value: minio-pv-claim
        repoRef:
          name: pipeline-manifests
          path: pipeline/minio
      name: minio
    - kustomizeConfig:
        parameters:
          - name: mysqlPvcName
            value: mysql-pv-claim
        repoRef:
          name: pipeline-manifests
          path: pipeline/mysql
      name: mysql
    - kustomizeConfig:
        repoRef:
          name: pipeline-manifests
          path: pipeline/persistent-agent
      name: persistent-agent
    - kustomizeConfig:
        repoRef:
          name: pipeline-manifests
          path: pipeline/pipelines-runner
      name: pipelines-runner
    - kustomizeConfig:
        # might need to remove this istio overlay
        overlays:
          - istio
        repoRef:
          name: pipeline-manifests
          path: pipeline/pipelines-ui
      name: pipelines-ui
    - kustomizeConfig:
        repoRef:
          name: pipeline-manifests
          path: pipeline/pipelines-viewer
      name: pipelines-viewer
    - kustomizeConfig:
        repoRef:
          name: pipeline-manifests
          path: pipeline/scheduledworkflow
      name: scheduledworkflow
    - kustomizeConfig:
        repoRef:
          name: pipeline-manifests
          path: pipeline/pipeline-visualization-service
      name: pipeline-visualization-service
  repos:
    - name: manifests
      uri: "https://github.com/opendatahub-io/odh-manifests/tarball/v0.8.0"
    - name: pipeline-manifests
      uri: "https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift"
  version: v0.8.0
