---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
    name: secret-generator
files:
    - realm.enc.yaml
    - clients/curator.enc.yaml
    - clients/devconfus2021.enc.yaml
    - clients/infra.enc.yaml
    - clients/rick.enc.yaml
    - clients/smaug.enc.yaml
    - clients/zero.enc.yaml
