kind: ResourceQuota
apiVersion: v1
metadata:
  name: vault-custom
spec:
  hard:
    requests.cpu: '2'
    requests.memory: 2Gi
    limits.cpu: '2'
    limits.memory: 2Gi
    requests.storage: 60Gi
    count/objectbucketclaims.objectbucket.io: 1
