apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common
- ../../../../base/config.openshift.io/oauths/cluster
- ../../../../base/user.openshift.io/groups/cluster-admins
- ../../../../base/core/configmaps/cluster-monitoring-config
- ../../../../base/core/namespaces/opf-alertreceiver
- ../../../../base/core/namespaces/openshift-storage
- ../../../../base/core/namespaces/openshift-local-storage
- ../../../../base/operators.coreos.com/operatorgroups/openshift-local-storage
- ../../../../base/operators.coreos.com/operatorgroups/openshift-storage
- ../../../../base/operators.coreos.com/subscriptions/openshift-local-storage-operator
- ../../../../base/operators.coreos.com/subscriptions/odf-operator


patchesStrategicMerge:
- groups/cluster-admins.yaml
- oauths/cluster_patch.yaml
- subscriptions/local-storage-operator_patch.yaml
- subscriptions/odf-operator_patch.yaml

generators:
- secret-generator.yaml
