---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - gitopsclusters
  - klusterletaddonconfigs
  - managedclusters
  - managedclustersetbindings
  - managedclustersets
  - placements
  - provider-connections
